---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags: clickhouse
- name: Install Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse
  tags: lighthouse
- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector
  tags: vector
