---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags: clickhouse

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  pre_tasks:
    - name: GIT | Install Dependencies
      ansible.builtin.yum:
        name: git
        state: present
    - name: Install nginx packages
      become: true
      ansible.builtin.yum:
        name:
          - nginx      
    - name: NGINX | Create general config
      become: true
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"

  roles:
    - lighthouse
  tags: lighthouse

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector
  tags: vector
